### ISSUE TITLE
Server not using edited config

### ISSUE THREAD

**Issue by ZeNyfh** [ZeithComms/Squake#1]
Java versions tested:
1.8.0_281
16.0.1

Forge versions tested: 
forge-1.16.5-36.1.25 
forge-1.16.5-36.0.53
forge-1.16.5-36.2.2
forge-1.16.5-36.2.0

The server does not create a .toml.bak file on tested versions >36.2.0
All versions were tested on newly made server
As the title says, the server only uses the default config and ignores any edited config values.

Video (optional) shows that the server reads the file but does not apply the config, also shows the console, 1.16.5-36.2.2 (latest) on jdk 1.8.0_281
https://youtu.be/7Y3Hisum4Fs

**Comment by squeek502** [comment]
I believe only the client-side config matters. All movement in Minecraft is handled on the client.
